# Generated by Django 5.2.4 on 2025-08-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at']},
        ),
    ]
